// prueba_angular/tienda/src/app/barra/barra.component.ts
import { Component, OnInit, Input} from '@angular/core';
import { CarritoComponent } from './../carrito/carrito.component';

@Component({
  selector: 'app-barra',
  templateUrl: './barra.component.html',
  styleUrls: ['./barra.component.css']
})
export class BarraComponent implements OnInit {

  constructor(private carritoComponent:CarritoComponent) { }

  ngOnInit() {

  }

  numeroProductoscarrito(){
    return this.carritoComponent.numero;
  }

}

<nav>
  <div class="nav-wrapper">
    <a href="/home" class="brand-logo">Tienda en línea</a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <li><a routerLink="/home">Inicio</a></li>
      <li><a routerLink="/carrito">Carrito de Compras <b>({{numeroProductoscarrito()}})</b></a></li>
      <li><a href="#">Cerrar sesión</a></li>
    </ul>
  </div>
</nav>

// prueba_react/tienda/src/Barra.jsx
import React from 'react';
import {Link} from "react-router-dom";
import * as request from 'superagent';

class Barra extends React.Component{

	constructor(props){
		super(props)

		this.state ={
			numProd:0
		}


		this.calcNumProd = this.calcNumProd.bind(this);
		this.calcNumProd();
	}


	componentWillReceiveProps(props){
		this.setState({numProd:props.numProdBarra})
	}

	render(){


		return(
			<div>
				<nav>
   					 <div className="nav-wrapper">
      						<a href="/home" className="brand-logo">Tienda On-Line</a>
      						<ul id="nav-mobile" className="right hide-on-med-and-down">
       							<li><Link to="/home">Inicio</Link></li>
        						<li><Link to="/carrito">Carrito <b>({this.state.numProd})</b></Link></li>
        						<li><Link to="">Cerrar sesión</Link></li>
      						</ul>
    					</div>
  				</nav>
			</div>
		)
	}

	calcNumProd(){

		request.get("http://localhost:8080/obtenerNumProdCarritoRc").end((err,res)=>{

			if(res.ok){
				this.setState({numProd:res.body.count})
			}
		})

	}
}

export default Barra;
