// prueba_angular/tienda/src/app/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { ProductosService } from './../productos.service';
import { Router, ActivatedRoute, ParamMap } from '@angular/router';
import { CarritoComponent } from './../carrito/carrito.component';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css'],
  providers:[ProductosService]
})
export class HomeComponent implements OnInit {

  productosJson = {
      productos:[]
  };

  constructor(private productosService:ProductosService, private carritoComponent:CarritoComponent) {}

  ngOnInit() {
        this.productosService.obtenerNumProdCarrito().subscribe((data) => {
          this.carritoComponent.numero = data['count'];
        });
  }

  ngAfterViewInit(){
    this.obtenerTodosProductos();
  }

  obtenerTodosProductos(){

    this.productosService.obtenerTodosProductos().subscribe((data)=>{

        for(let idx in data){
          this.productosJson.productos.push(data[idx]);
        }

    })

  }


  buscarProd(valor:string){

    this.productosJson.productos = [];

    this.productosService.obtenerProductoMatch({'nombre':valor}).subscribe((data)=>{

        for(let idx in data){
          this.productosJson.productos.push(data[idx]);
        }

    })
  }

  agregarCarrito(numProductos:number, nombreProd:string, precio:string){
    let subtotal = Number(numProductos) * Number(precio);
    this.productosService.agregarProductoCarrito({'numero':numProductos,'nombre':nombreProd,'precio':precio,'subtotal':subtotal}).subscribe(data => {

        if(data['status'] == 200)
          this.carritoComponent.numero = Number(this.carritoComponent.numero) +  Number(numProductos);

    });

  }


}

<app-barra></app-barra>
<div class="container">
  <h4>Catalogo de Productos</h4>
  <div class="row">

    <div class="input-field">
        <input placeholder="Buscar producto" type="text" #inputBuscar id="buscarProd" (keyup)="buscarProd(inputBuscar.value)">
    </div>

    <div *ngFor="let prod of productosJson.productos" class="col l3 m3 s12" >

      <div class="card" *ngIf="prod.visible">
        <div class="card-image">
          <img src="./assets/img/{{prod.imagen}}" width="200" height="200" />
        </div>
        <div class="card-content">
          <h5>{{prod.nombre}}</h5>
          <ul>
              <li>Precio : ${{prod.precio}}</li>
              <li>Unidades Disponibles : {{prod.unidades}}</li>
          </ul>
        </div>
        <div class="card-action">
          <div class="row">
            <div class="col l6">
              <button class="btn" routerLink="/detalleProducto/{{prod.nombre}}">Ver más</button>
            </div>
            <div class="col l6">
            <button (click)="agregarCarrito(input.value,prod.nombre,prod.precio)" class="btn">Añadir</button>
            </div>
          </div>
          <input type="number" min="1" name="unidades" value="" #input placeholder="Unidades">
        </div>
      </div>

    </div>
   </div>
</div>

// prueba_react/tienda/src/Home.jsx
import React from 'react';
import Barra from './Barra.jsx';
import * as request from 'superagent';
import './Home.css';
import DetalleProd from './DetalleProd.jsx';

class Home extends React.Component{

	constructor(){
		super()

		this.state = {

				productos : [],
				prouctoVer:{},
				numProdCarrito:0,
				prodCarrito:'',
				precioProdCarrito:'',
				numProdBarra:0
		}

		this.obtenerProductos();

		this.obtenerProductoMatch = this.obtenerProductoMatch.bind(this);
		this.verProducto = this.verProducto.bind(this);
		this.volverHome = this.volverHome.bind(this);
		this.sumarProductos = this.sumarProductos.bind(this);
		this.addCarrito = this.addCarrito.bind(this);
		this.calcularNumProd = this.calcularNumProd.bind(this);
		this.calcularNumProd();
	}

	render(){

		if(this.state.productoVer){
			return <DetalleProd prod={this.state.productoVer} mtdVolver={this.volverHome} obtenerImagen={this.obtenerImagen} />
			//return(<div><h3>Ver Producto</h3><button className="btn" onClick={this.volverHome}>Volver</button></div>);
		}else{

		 return(
			<div>
			<Barra numProdBarra={this.state.numProdBarra} calcularNumProd={this.calcularNumProd}/>
			<div className="container">

				<h4>Catálogo de productos</h4>

				<input type="text" placeholder="Buscar producto" onChange={this.obtenerProductoMatch} />

				 <div className="row">
        				{this.state.productos.map(item => (
       						<div className="col l3 m12 s12" key={item.nombre}>
						<div  key={item.nombre} className="card">
      							<div className="card-image">
							<img src={this.obtenerImagen(item.imagen)} alt="img" className="imagen-producto" />
							</div>
        						<div className="card-content">
          								<h5>{item.nombre}</h5>
									<p>Precio: {item.precio}</p>
									<p>Unidades Disponibles: {item.unidades}</p>
        						</div>
        						<div className="card-action">
          								<button className="btn" onClick={this.verProducto} data-nombre={item.nombre}>Ver más</button>
									<input type="text" onChange={this.sumarProductos} data-prod={item.nombre} data-precio={item.precio} placeholder="Ingrese número de productos" />
									<button className="btn" onClick={this.addCarrito}>Añadir</button>
        						</div>
    						</div>
						</div>
					))}
      				 </div>

			</div>
			</div>
		 )
		}
	}

	calcularNumProd(){

		 request.get("http://localhost:8080/obtenerNumProdCarritoRc").end((err,res)=>{

                        if(res.ok)
                                this.setState({numProdBarra:res.body.count})
                })

	}

	addCarrito(){

		let subTotal = this.state.numProdCarrito * this.state.precioProdCarrito;

		request.post("http://localhost:8080/agregarCarritoRc").send({"numero":this.state.numProdCarrito,"nombre":this.state.prodCarrito,"precio":this.state.precioProdCarrito,"subtotal":subTotal}).end((err,res)=>{
			//this.setState({numProdBarra:this.state.numProdBarra + parseInt(this.state.numProdCarrito)})
			this.calcularNumProd();
		})
	}

	sumarProductos(e){
		this.setState({
			numProdCarrito: e.target.value, prodCarrito:e.target.getAttribute("data-prod"),precioProdCarrito:e.target.getAttribute("data-precio")})

	}


	volverHome(){
		this.setState({productoVer:null});
	}

	obtenerProductos(){

		request.get('http://localhost:8080/obtenerProductosRc').end((err,res)=>{

			if(err || !res.ok)
				console.log('Error');

			res.body.forEach((val)=>{
				this.setState({ productos : this.state.productos.concat(val)})
			})

		})
	}

	obtenerImagen(nombre){

		var imagen = require('./img/'+nombre);
		return imagen;

	}


	obtenerProductoMatch(e){
		let data = {"nombre":e.target.value}

		this.setState({ productos : [] })

		request.post('http://localhost:8080/buscarProductoMatchRc').send(data).end((err,res)=>{

			if(err || !res.ok)
				console.log(err);

			 res.body.forEach((val)=>{
                                this.setState({ productos : this.state.productos.concat(val)})
                        })
		})

	}

	verProducto(e){

		request.post('http://localhost:8080/obtenerProductoRc').send({"nombre":e.target.getAttribute("data-nombre")}).end((err,res)=>{

			this.setState({productoVer : res.body[0]});

		})


		
	}

}

export default Home;
